export const LOAD_PRODUCT_LIST = "LOAD_PRODUCT_LIST";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const CHANGE_WISHLIST_SIZE = "CHANGE_WISHLIST_SIZE";
export const SET_COUPON_CODE = "SET_COUPON_CODE";
